name: Manual Update
on: [ workflow_dispatch ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses : actions/checkout@v3
    - name : Setup Python
      uses : actions/setup-python@v3
      with : 
        python-version : "3.8"

    - name : Install Dependencies
      run : |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name : Run AtCoder AutoClone
      run : |
        python src/init_exec.py
        ls
    
    - name : Commit and Push
      id : git_update
      continue-on-error: true
      run : |
        git config user.name "kaigitt"
        git config user.email "s12201600350@gmail.com"
        git add .
        git commit -m "Added my codes from AtCoder"
        git pull
        git push origin main
        
    - name : Error Handling
      if : ${{steps.git_update.outcome == 'failure'}}
      run : |
        echo "No new submissions found. Your repo were not updated"
        
